development:
  host: localhost
  adapter: postgresql
  database: vesna_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: vesna_production
  pool: 5
  timeout: 5000

test:
  host: localhost
  adapter: postgresql
  database: vesna_test
  pool: 5
  timeout: 5000
